# QBR-0006-ZKu.graphql
# Query voor uitvoerend Zorgkantoor op Bemiddelingsregister
# Verplichte input:
#   - bemiddelingspecificatieID - eigen bemiddelingsspecificatie
#   - uzovicode zorgkantoor
#   - toewijzing Ingangsdatum bijv. 2020-02-19
#   - vaststelling moment bijv. 2020-02-09T13:47:16.000+01:00
#   - dag vaststelling moment bijv. 2020-02-09


query Bemiddelingspecificatie(
    $bemiddelingspecificatieId: UUID!
    $uitvoerendZorgkantoor: String!
    $toewijzingIngangsdatum: Date!
    $vaststellingMoment: DateTime! 
    $dagVaststellingMoment: Date!
) {
    bemiddelingspecificatie(
        where: {
            bemiddelingspecificatieID: { eq: $bemiddelingspecificatieId }
            uitvoerendZorgkantoor: { eq: $uitvoerendZorgkantoor }
            toewijzingIngangsdatum: { eq: $toewijzingIngangsdatum }
            vaststellingMoment: {eq: $vaststellingMoment }
            toewijzingEinddatum: { eq: null } 
        }
    ) {
        bemiddelingspecificatieID
        leveringsvorm
        zzpCode
        toewijzingIngangsdatum
        toewijzingEinddatum
        instelling
        uitvoerendZorgkantoor
        vaststellingMoment
        percentage
        opname
        redenIntrekking
        etmalen
        instellingBestemming
        soortToewijzing
        bemiddeling {
            bemiddelingID
            wlzIndicatieID
            verantwoordelijkZorgkantoor
            verantwoordelijkheidIngangsdatum
            verantwoordelijkheidEinddatum
            client {
                bsn
                contactpersoon(
                    where: {
                        and: [
                            {
                                or: [{ einddatum: { eq: null } }, 
                                { einddatum: { gte: $toewijzingIngangsdatum } },
                                { einddatum: {gte: $dagVaststellingMoment }}]
                            }
                        ]
                    }
                ) {
                    contactpersoonID
                    relatienummer
                    volgorde
                    soortRelatie
                    rol
                    relatie
                    geslachtsnaam
                    voorvoegselGeslachtsnaam
                    partnernaam
                    voorvoegselPartnernaam
                    voornamen
                    voorletters
                    roepnaam
                    naamgebruik
                    geslacht
                    geboortedatum
                    geboortedatumgebruik
                    ingangsdatum
                    einddatum
                    contactgegevens(
                        where: {
                            and: [
                                {
                                    or: [{ einddatum: { eq: null } }, 
                                    { einddatum: { gte: $toewijzingIngangsdatum } },
                                    { einddatum: {gte: $dagVaststellingMoment }}]
                                }
                            ]
                        }
                    ) {
                        contactpersoonContactgegevensID
                        adressoort
                        straatnaam
                        huisnummer
                        huisletter
                        huisnummertoevoeging
                        postcode
                        plaatsnaam
                        land
                        aanduidingWoonadres
                        emailadres
                        telefoonnummer01
                        landnummer01
                        telefoonnummer02
                        landnummer02
                        ingangsdatum
                        einddatum
                    }
                }
                leefeenheid
                huisarts
                communicatievorm
                taal
                contactgegevens(
                    where: {
                        and: [
                            {
                                or: [{ einddatum: { eq: null } }, 
                                { einddatum: { gte: $toewijzingIngangsdatum } },
                                { einddatum: {gte: $dagVaststellingMoment }}]
                            }
                        ]
                    }
                ) {
                    clientContactgegevensID
                    adressoort
                    straatnaam
                    huisnummer
                    huisletter
                    huisnummertoevoeging
                    postcode
                    plaatsnaam
                    land
                    aanduidingWoonadres
                    emailadres
                    telefoonnummer01
                    landnummer01
                    telefoonnummer02
                    landnummer02
                    ingangsdatum
                    einddatum
                }
                clientID
            }
            bemiddelingspecificatie(
                    where: {
                        and: [
                            {
                                or: [{ toewijzingEinddatum: { eq: null } }, 
                                { toewijzingEinddatum: { gte: $toewijzingIngangsdatum } },
                                { toewijzingEinddatum: {gte: $dagVaststellingMoment }}]
                            }
                        ]
                    }
                ) {
                bemiddelingspecificatieID
                leveringsvorm
                zzpCode
                toewijzingIngangsdatum
                toewijzingEinddatum
                instelling
                uitvoerendZorgkantoor
                vaststellingMoment
                percentage
                pgbPercentage
                opname
                redenIntrekking
                etmalen
                instellingBestemming
                soortToewijzing
            }
            regiehouder(
                    where: {
                        and: [
                            {
                                or: [{ einddatum: { eq: null } }, 
                                { einddatum: { gte: $toewijzingIngangsdatum } },
                                {einddatum: {gte: $dagVaststellingMoment }}]
                            }
                        ]
                    }
                ) {
                    regiehouderID
                    instelling
                    ingangsdatum
                    einddatum
                    regierol
                }
        }
    }
}
