# QBR-silvester_AW33.graphql
# Query voor Silvester om de AW33 aan te kunnen maken
# Verplichte input:
#   - bemiddelingID = UUID
#   - selectiedatum = date
#   - vorigeSelectiemoment = datetime
# Selecteer van een Bemiddeling op basis van BemiddelingID
# 1. De Bemiddeling
# 2. De Bemiddelingspecificaties waarvan OF
#    a. Het vaststellingsmoment > het laatste selectiemoment
#    b. (einddatum = leeg OF einddatum >= selectiedatum) EN vaststellingsmoment <= vorigeSelectiemoment
# 3. De regiehouder waarvan EN
#    a. ingangsdatum <= selectiedatum
#    b. einddatum = leeg OF einddatum > selectiedatum
# 4. Client bij de Bemiddeling
# 5. ClientContactgegevens waarvan: einddatum = leeg OF einddatum >= selectiedatum
# 6. Contactpersoon waarvan: einddatum = leeg OF einddatum >= selectiedatum
# 7. ContactpersoonContactgegevens waarvan: einddatum = leeg OF einddatum >= selectiedatum

query Bemiddeling(
  $BemiddelingID: UUID!
  $vorigeSelectiemoment: DateTime!
  $Selectiedatum: Date!
) {
  bemiddeling(where: { bemiddelingID: { eq: $BemiddelingID } }) {
    bemiddelingID
    wlzIndicatieID
    verantwoordelijkZorgkantoor
    bemiddelingspecificatie(
      where: {
        or: [
          { vaststellingMoment: { gt: $vorigeSelectiemoment } }
          {
            and: [
              { vaststellingMoment: { lte: $vorigeSelectiemoment } }
              {
                or: [
                  { toewijzingEinddatum: { eq: null } }
                  { toewijzingEinddatum: { lte: $Selectiedatum } }
                ]
              }
            ]
          }
        ]
      }
    ) {
      bemiddelingspecificatieID
      toewijzingIngangsdatum
      toewijzingEinddatum
      instelling
      uitvoerendZorgkantoor
      vaststellingMoment
    }
  }
}
