query Bemiddeling(
  $WlzIndicatieID: UUID! # afkomstig uit query
  $uzovicodeUitvoerendzorgkantoor: String! # afkomstig uit Access-token
) {
  bemiddeling(
    where: {
      and: [ {
         wlzIndicatieID: { eq: $WlzIndicatieID }
         verantwoordelijkZorgkantoor:  {
            neq: $uzovicodeUitvoerendzorgkantoor
         }
         bemiddelingspecificatie:  {
            all:  {
               uitvoerendZorgkantoor:  {
                  eq: $uzovicodeUitvoerendzorgkantoor
               }
            }
         }
      }]
    }
  ) {
      wlzIndicatieID
      bemiddelingspecificatie {
        uitvoerendZorgkantoor
      }
    }
}