@startuml

start

:Ontvangst notificatie:\nNIEUWE_BEMIDDELINGSPECIFICATIE_ZORGAANBIEDER;

:Raadpleeg Bemiddelingspecificatie, Bemiddeling en Client:;

#lightgreen:__QBR-0001-ZA__;

stop

start

:Raadpleeg aanvullende Bemiddelingspecificaties\n(Informatieve zorgtoewijzingen));

if (toewijzingEinddatum eigen bemiddelingspecficatie gevuld? \n(uit QBR-001-ZA)) then (ja)
  #lightgreen:__QBR-0002-ZA__;
else (nee)
  #lightgreen:__QBR-0003-ZA__;
endif

stop

@enduml