# QBR-0002-ZA.graphql
# Query voor Zorgaanbieder op Bemiddelingsregister
# Verplichte input:
#   - bemiddelingspecificatieID
#   - agbcode instelling
#   - toewijzing Ingangsdatum bijv. 2020-02-19
#   - vaststelling moment bijv. 2020-02-09T13:47:16.000+01:00
#   - dag vaststelling moment bijv. 2020-02-09
#   - toewijzing Einddatum bijv. 2024-03-17


# Query
query Bemiddelingspecificatie(
  $BemiddelingspecificatieID: UUID!
  $Instelling: String!
  $ToewijzingIngangsdatum: Date!
  $VaststellingMoment: DateTime!
  $DagVaststellingMoment: Date!
  $ToewijzingEinddatum: Date!
  
) {
  bemiddelingspecificatie(
    where: {
      bemiddelingspecificatieID: { eq: $BemiddelingspecificatieID }
      instelling: { eq: $Instelling }
      toewijzingIngangsdatum: { eq: $ToewijzingIngangsdatum }
      vaststellingMoment: { eq: $VaststellingMoment } 
      toewijzingEinddatum: { eq: $ToewijzingEinddatum }
    }
  ) {
    bemiddelingspecificatieID
    leveringsvorm
    zzpCode
    toewijzingIngangsdatum
    toewijzingEinddatum
    instelling
    uitvoerendZorgkantoor
    vaststellingMoment
    percentage
    opname
    redenIntrekking
    etmalen
    instellingBestemming
    soortToewijzing
    bemiddeling {
      bemiddelingID
      wlzIndicatieID
      verantwoordelijkZorgkantoor
      verantwoordelijkheidIngangsdatum
      verantwoordelijkheidEinddatum
      client {
        bsn
        contactpersoon(
          where: {
            and: [
              {
                or: [
                  { einddatum: { eq: null } }
                  { einddatum: { gte: $ToewijzingIngangsdatum } }
                  { einddatum: { gte: $DagVaststellingMoment } }
                ]
              }
              { ingangsdatum: { ngt: $ToewijzingEinddatum } }
            ]
          }
        ) {
          contactpersoonID
          relatienummer
          volgorde
          soortRelatie
          rol
          relatie
          geslachtsnaam
          voorvoegselGeslachtsnaam
          partnernaam
          voorvoegselPartnernaam
          voornamen
          voorletters
          roepnaam
          naamgebruik
          geslacht
          geboortedatum
          geboortedatumgebruik
          ingangsdatum
          einddatum
          contactgegevens(
            where: {
              and: [
                {
                  or: [
                    { einddatum: { eq: null } }
                    { einddatum: { gte: $ToewijzingIngangsdatum } }
                    { einddatum: { gte: $DagVaststellingMoment } }
                  ]
                }
                { ingangsdatum: { ngt: $ToewijzingEinddatum } }
              ]
            }
          ) {
            contactpersoonContactgegevensID
            adressoort
            straatnaam
            huisnummer
            huisletter
            huisnummertoevoeging
            postcode
            plaatsnaam
            land
            aanduidingWoonadres
            emailadres
            telefoonnummer01
            landnummer01
            telefoonnummer02
            landnummer02
            ingangsdatum
            einddatum
          }
        }
        leefeenheid
        huisarts
        communicatievorm
        taal
        contactgegevens(
          where: {
            and: [
              {
                or: [
                  { einddatum: { eq: null } }
                  { einddatum: { gte: $ToewijzingIngangsdatum } }
                  { einddatum: { gte: $DagVaststellingMoment } }
                ]
              }
              { ingangsdatum: { ngt: $ToewijzingEinddatum } }
            ]
          }
        ) {
          clientContactgegevensID
          adressoort
          straatnaam
          huisnummer
          huisletter
          huisnummertoevoeging
          postcode
          plaatsnaam
          land
          aanduidingWoonadres
          emailadres
          telefoonnummer01
          landnummer01
          telefoonnummer02
          landnummer02
          ingangsdatum
          einddatum
        }
        clientID
      }
      bemiddelingspecificatie(
        where: {
          and: [
            {
              or: [
                { toewijzingEinddatum: { eq: null } }
                { toewijzingEinddatum: { gte: $ToewijzingIngangsdatum } }
                { toewijzingEinddatum: { gte: $DagVaststellingMoment } }
              ]
            }
            { toewijzingIngangsdatum: { ngt: $ToewijzingEinddatum } }
          ]
        }
      ) {
        bemiddelingspecificatieID
        leveringsvorm
        zzpCode
        toewijzingIngangsdatum
        toewijzingEinddatum
        instelling
        uitvoerendZorgkantoor
        vaststellingMoment
        percentage
        opname
        redenIntrekking
        etmalen
        instellingBestemming
        soortToewijzing
      }
      regiehouder(
          where: {
            and: [
              {
                or: [
                  { einddatum: { eq: null } }
                  { einddatum: { gte: $ToewijzingIngangsdatum } }
                  { einddatum: { gte: $DagVaststellingMoment } }
                ]
              }
              { ingangsdatum: { ngt: $ToewijzingEinddatum } }
            ]
          }
        ) {
          regiehouderID
          instelling
          ingangsdatum
          einddatum
          regierol
        }
      }
    }
  }

