openapi: 3.0.1
info:
  title: Wlz bemiddeling register
  description: OpenAPI Koppelvlak specificatie tbv Wlz bemiddeling register.
  termsOfService: 'https://github.com/OAI/OpenAPI-Specification/blob/master/LICENSE'
  contact:
    name: "iStandaarden"
    url: "https://istandaarden.nl"
    email: info@istandaarden.nl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: '0.0.1'
externalDocs:
  description: Find out more about OpenAPI
  url: 'https://www.openapis.org'
servers:
  - url: 'https://api.zk.nl/wlzbemiddelingregister'
tags:
  - name: Wlz bemiddeling
    description: 'Alles over Wlz bemiddeling'
    externalDocs:
      description: Link naar iStandaarden
      url: 'https://informatiemodel.istandaarden.nl/'
  - name: "iWlz codelijsten"
    description: ""
    externalDocs:
      description: "Codelijsten bij iWlz 2.2"
      url: "https://www.istandaarden.nl/ibieb/codelijsten-iwlz-221"
paths:
  /wlzbemiddelingen:
    get:
      tags:
        - Wlz bemiddelingen
      summary: Vind bemiddelingID's op BSN.
      description: Vind bemiddelingID's van verstrekte bemiddelingen op basis van het BSN van de cliënt.
      operationId: getWlzbemiddelingen
      parameters:
        - in: header
          name: X-orgKey
          description: Uniek ID van de organisatie binnen het netwerk
          schema:
            type: integer
            format: int32
          required: true
        - in: header
          name: X-PSID
          description: Pseudo ID van client
          schema:
            type: integer
            format: int32
          required: true
        - in: header
          name: X-Request-ID
          description: Identificatie van het request
          schema:
            type: string
          required: true
        - name: bsn
          in: query
          description: BSN van Wlz bemiddelde client
          required: true
          schema:
            type: string
            pattern: '^[0-9]{9}$'
            example: 950032153
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/WlzbemiddelingIDs'
            application/json:
              schema:
                $ref: '#/components/schemas/WlzbemiddelingIDs'
        '400':
          description: Ongeldig BSN
          content: {}
        '404':
          description: Geen Wlz bemiddelingen gevonden
          content: {}
  /wlzbemiddelingen/{wlzbemiddelingID}:
    get:
      tags:
        - Wlz bemiddelingen
      summary: Vind Wlz bemiddeling op wlzbemiddelingID.
      description: De Wlz bemiddeling bevat de Wlz bemiddelinggegevens van de cliënt.
      operationId: getWlzbemiddelingByID
      parameters:
        - in: header
          name: X-orgKey
          description: Uniek ID van de organisatie binnen het netwerk
          schema:
            type: integer
            format: int32
          required: true
        - in: header
          name: X-PSID
          description: Pseudo ID van client
          schema:
            type: integer
            format: int32
          required: true
        - in: header
          name: X-Request-ID
          description: Identificatie van het request
          schema:
            type: string
          required: true
        - name: wlzbemiddelingID
          in: path
          description: Uniek ID van de Wlz bemiddeling
          required: true
          schema:
            type: string
            format: uuid
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Wlzbemiddeling'
            application/json:
              schema:
                $ref: '#/components/schemas/Wlzbemiddeling'
        '400':
          description: Ongeldig Wlz bemiddeling ID
          content: {}
        '404':
          description: Onbekend Wlz bemiddeling ID
          content: {}
components:
  schemas:
    Wlzbemiddeling:
      required:
        - bemiddelingID
        - bsn
        - statusBemiddeling
        - ontvangstdatum
      type: object
      properties:
        bemiddelingID:
          type: string
          format: uuid
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        bsn:
          type: string
          pattern: '^[0-9]{9}$'
          example: 950032153
        statusBemiddeling:
          description: "De status van de bemiddeling"
          type: string
          enum: ["Ontvangen","In behandeling","Afgerond","Cliënt ziet af van zorg"]
        Leveringsvorm:
          description: "Gecodeerde aanduiding van de vorm waarin zorg binnen de Wlz geleverd kan worden"
          type: string
          enum: ["4","5","7","8","9"]
          example: 4
        ontvangstdatum:
          description: "De datum waarop het verzoek tot bemiddeling is ontvangen"
          type: string
          format: date
        ingangsdatum:
          description: "De datum waarop het zorgkantoor start met bemiddelen"
          type: string
          format: date
        einddatum:
          description: "De datum waarop het zorgkantoor de bemiddeling heeft afgerond"
          type: string
          format: date 
        overdrachtsdatum:
          description: "De datum vanaf wanneer het nieuwe zorgkantoor verantwoordelijk is"
          type: string
          format: date
        zorgkantoorOverdracht: 
          description: "Verantwoordelijk zorgkantoor vanaf dossieroverdracht (Moet voldoen aan COD001: Zorgkantoor; zie iWlz codelijsten)"
          type: string
          example: 5501
        zorgaanbieder:
          $ref: '#/components/schemas/Zorgaanbieders'
        pgb:
          $ref: '#/components/schemas/Pgb'
      xml:
        name: wlzbemiddeling
    Pgb:
      required:
        - Status
      type: object
      properties:
        Status:
          description: "Status pgb"
          type: string
          enum: ["Ontvangen", "In Behandeling", "Toegekend", "Geen pgb"]
          example: "Geen pgb"
        BedragPgb:
          type: integer
        Ingangsdatum:
          type: string
          format: date
        Einddatum:
          type: string
          format: date
      xml:
        name: pgb
    WlzbemiddelingID:
      type: string
      format: uuid
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      xml:
        name: wlzbemiddelingID
    WlzbemiddelingIDs:
      type: array
      items:
        $ref: '#/components/schemas/WlzbemiddelingID'
      xml:
        name: wlzbemiddelingIDs
        wrapped: true
    Zorgaanbieder:
      required:
        - zorgaanbieder
        - ingangsdatum
      type: object
      properties:
        Zorgaanbieder:
          description: "De zorgaanbieder waarnaar de cliënt bemiddeld is (volgens iWlz-agbcodelijst)"
          type: string
          pattern: '^[0-9]{8}$'
        Ingangsdatum:
          description: "De datum die aangeeft vanaf welke datum de client naar de instelling bemiddeld is"
          type: string
          format: date
        Opname:
          description: "Aanduiding waarmee wordt aangegeven of zorgaanbieder het opnamedeel, binnen leveringsvorm (deeltijd)verblijf, levert"
          type: boolean
      xml:
        name: zorgaanbieder
    Zorgaanbieders:
      type: array
      items:
        $ref: '#/components/schemas/Zorgaanbieder'
      xml:
        name: zorgaanbieders
        wrapped: true



             



